
sudo: required		
 language: go		
 go:		
   - 1.3		
   - master		
 		
 services:		
   - docker		
 		
 before_install:		
   - docker build -t adg1/outyet .		
   - docker run --publish 6060:8080 adg1/outyet		
   - docker ps -a
